# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.5'

- script: sudo apt-get update
- script: sudo apt-get install -y openjfx
- script: sudo apt-get install -y ruby-dev
- script: sudo apt-get install zlib1g-dev
- script: mvn clean install
- script: gem install hiptest-publisher
- script: hiptest-publisher -c junit.conf --token=30312522457421115545281733546832459934050145661703934293 --only=tests --test-run-id=242663
  displayName: 'Install hiptest-publisher'
- script: mvn package 
  displayName: 'Run tests'
- script: hiptest-publisher -c junit.conf --token=30312522457421115545281733546832459934050145661703934293 -p "target/surefire-reports/TEST-com.coffeemachine.*.xml" --test-run-id=242663
  displayName: 'Push tests to HipTest'

